### ISSUE TITLE
Overlapping folders in sidebar

### ISSUE THREAD

**Issue by orschiro** [piqus/sublime-elementary#3]
Dear @piqus, 

I noticed another issue with the sidebar. Folders are overlapping:

![image](https://cloud.githubusercontent.com/assets/170947/8164967/e91b1172-138c-11e5-882e-a620cd8d9b76.png)

Can you confirm this?

Regards,

Robert

**Comment by piqus** [comment]
Very interesting bug. I am very curious how to reproduce it, could you try explain when you encountered this bug and what steps you've done?

:+1: For noticing it.

**Comment by orschiro** [comment]
1. On the command-line switch into a folder
2. From there open `$ subl .`

This causes the issue for me.

**Comment by piqus** [comment]
Oh, I guess you have version of Sublime Text 2 not a ST3, right? It could be also connected with #2 which is only noticeable on `"theme": "Elementary Light.sublime-theme"` not on `"theme": "Elementary Light 3.sublime-theme"`.

**Comment by piqus** [comment]
Probably it is a just bug connected with SublimeText core (reported in SublimeTextIssues/Core#62 scroll-down to hArpanet, whatisjasongoldstein posts). I assume it is also present in ST3 I am going to investigate closely, but unfortunately I can't promise anything which is connected with #3.

**Comment by orschiro** [comment]
No, I am using ST3 with the following user settings:

```
"overlay_scroll_bars": "enabled",
	"save_on_focus_lost": true,
	"spell_check": true,
	"tabs_small": true,
	"theme": "Elementary Light 3.sublime-theme"
```

They should be correct, right?

**Comment by piqus** [comment]
Yes, it is okay. As it was aforementioned in post above - I barely can do something :(

**Comment by orschiro** [comment]
> Yes, it is okay. As it was aforementioned in post above - I barely can do something :(

No problem! I am grateful for your time spent on this.

As a workaround I switched to the dark theme and will see now if the problem still occurs.

**Comment by piqus** [comment]
:+1:

**Comment by piqus** [comment]
@sentience in SublimeTextIssues/Core#62 have posted simple workaround:

> 1. Launch Sublime Text 3.
2. Open one of your projects.
3. Project > New Workspace for Project.
4. Close the old window.
5. Ensure View > Side Bar > Hide Open Files is unchecked.
6. Project > Close Project.
7. Quit Sublime Text 3.

>Repeat steps 1-7 for each of your projects.

**Comment by piqus** [comment]
I am closing this issue, but please reopen if you mind that workaround does not work.

**Comment by orschiro** [comment]
@piqus 

Thanks for the reference! I switched to Atom editor, however.
